# clamav-milter.conf(5) configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

# Main options
User {User}
Foreground {Foreground}
PidFile {PidFile}
SupportMultipleRecipients {SupportMultipleRecipients}
TemporaryDirectory {TemporaryDirectory}
FixStaleSocket {FixStaleSocket}
MilterSocket {MilterSocket}
MilterSocketGroup {MilterSocketGroup}
MilterSocketMode {MilterSocketMode}
ReadTimeout {ReadTimeout}

# Clamd options
ClamdSocket {ClamdSocket}

# Exclusions options
MaxFileSize {MaxFileSize}

# Actions options
AddHeader {AddHeader}
OnClean {OnClean}
OnInfected {OnInfected}
OnFail {OnFail}
RejectMsg {RejectMsg}

# Logging options
LogSyslog  {LogSyslog}
LogFacility {LogFacility}
LogVerbose {LogVerbose}
LogInfected {LogInfected}
LogClean {LogClean}
LogRotate {LogRotate}
LogFile {LogFile}
LogTime {LogTime}
LogFileUnlock {LogFileUnlock}
LogFileMaxSize {LogFileMaxSize}




