#!/usr/bin/perl

# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010-2018 Laurent Declercq <l.declercq@nuxwin.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

# Wrap real i-MSCP installer for satisfying pre-requisites

use strict;
use warnings;
use POSIX qw/ locale_h /;

unshift @INC, 'engine/PerlLib';

$ENV{'LANG'} = 'C.UTF-8';
setlocale( LC_MESSAGES, 'C.UTF-8' );

sub prntInfo
{
    print STDOUT "[\x1b[0;34mINFO\x1b[0m] @_\n";
}

sub prntError
{
    print STDERR "[\x1b[0;31mERROR\x1b[0m] @_\n";
    exit 1;
}

$> == 10 or prntError( 'The i-MSCP installer must be run with the privileges of super user.' );

chomp( our $ROOTDIR = `realpath \$(dirname @{ [ __FILE__ ]} 2>/dev/null)` );
chdir( $ROOTDIR ) or prntError( sprintf( "couldn't chdir: %s", $! || 'Unknown error' ));

DIST_BOOTSTRAP:

my $forceDistBootstrap;
if ( $forceDistBootstrap || !-f '/etc/imscp/imscp.conf' ) {
    my ($bootstrapDir, $bootstrapFile) = ( 'installer/bootstrap' );

    if ( -f '/etc/debian_version' || -f '/etc/devuan_version' ) {
        $bootstrapFile = 'debian.pl';
    } elsif ( -f '/etc/mageia-release' ) {
        $bootstrapFile = 'mageia.pl';
    } elsif ( -f '/etc/redhat-release' ) {
        $bootstrapFile = 'redhat.pl';
    } elsif ( -f '/etc/os-release' && `grep -q openSUSE /etc/os-release` ) {
        $bootstrapFile = 'opensuse.pl';
    } elsif ( -f '/etc/arch-release' || -f '/etc/manjaro-release' ) {
        $bootstrapFile = 'archlinux.pl';
    } elsif ( -f '/etc/gentoo-release' ) {
        $bootstrapFile = 'gentoo.pl';
    } else {
        prntError( 'Your distribution is not known yet. Please contact the i-MSCP team.' );
    }

    -f "$bootstrapDir/$bootstrapFile" or prntError(
        "No installer bootstrap file found for your distribution. You need first implement the $bootstrapDir/$bootstrapFile bootstrap file."
    );

    do "$bootstrapDir/$bootstrapFile" or prntError( sprintf( "Couldn't bootstrap the i-MSCP installer: %s", $@ || $! ));
} else {
    eval {
        require iMSCP::Requirements;
        iMSCP::Requirements->new()->all();
    };
    if ( $@ ) {
        $forceDistBootstrap = 1;
        goto DIST_BOOTSTRAP;
    }
}

prntInfo 'Generating *.ph Perl header files from *.h C header files...';
system(
    "rm -fR $ROOTDIR/engine/PerlLib/include/* && cd /usr/include; h2ph -a -d $ROOTDIR/engine/PerlLib/include syscall.h linux/fs.h"
) == 0 or prntError(
    "Couldn't generate required Perl header files"
);

# Execute the real installer
exec( '/usr/bin/perl', 'installer/installer.pl', @ARGV );

__END__
