<div id="login">
    <form name="login" action="index.php" method="post">
        <table>
            <tr>
                <td class="left">
                    <label for="admin_name"><?= $this->form->get('admin_name')->getLabel() ?></label>
                </td>
                <td class="right"><input type="text" name="admin_name" id="admin_name" value="<?= $this->form->get('admin_name')->getValue() ?>"></td>
            </tr>
            <tr>
                <td class="left"><label for="admin_pass"><?= $this->form->get('admin_pass')->getLabel() ?></label></td>
                <td class="right"><input type="password" name="admin_pass" id="admin_pass" value=""></td>
            </tr>
            <tr>
                <td colspan="2" class="right">
                    <input type="hidden" name="csrf" value="<?= $this->form->get('csrf')->getValue() ?>">
                    <button type="submit" name="Submit" tabindex="3"><?= $this->form->get('submit')->getLabel() ?></button>
                </td>
            </tr>
            <!-- BDP: ssl_block -->
            <tr>
                <td colspan="2" class="center">
                    <br>
                    <a class="icon {SSL_IMAGE_CLASS}" href="{SSL_LINK}" title="{TR_SSL_DESCRIPTION}">{TR_SSL}</a>
                </td>
            </tr>
            <!-- EDP: ssl_block -->
        </table>
    </form>
</div>
