<div id="login">
    <form name="<?= toHtml($this->form->getName(), 'htmlAttr') ?>" method="post">
        <table>
            <tr>
                <td class="left">
                    <label for="admin_name"><?= $this->form->get('admin_name')->getLabel() ?></label>
                </td>
                <td class="right"><input type="text" name="admin_name" id="admin_name" value="<?= toHtml($this->form->get('admin_name')->getValue(), 'htmlAttr') ?>"></td>
            </tr>
            <tr>
                <td class="left"><label for="admin_pass"><?= toHtml($this->form->get('admin_pass')->getLabel()) ?></label></td>
                <td class="right"><input type="password" name="admin_pass" id="admin_pass" value=""></td>
            </tr>
            <tr>
                <td colspan="2" class="right">
                    <input type="hidden" name="csrf" value="<?= toHtml($this->form->get('csrf')->getValue(), 'htmlAttr') ?>">
                    <button type="submit" name="submit" tabindex="3"><?= toHtml($this->form->get('submit')->getLabel()) ?></button>
                </td>
            </tr>
            <!-- BDP: ssl_block -->
            <tr>
                <td colspan="2" class="center">
                    <br>
                    <a class="icon {SSL_IMAGE_CLASS}" href="{SSL_LINK}" title="{TR_SSL_DESCRIPTION}">{TR_SSL}</a>
                </td>
            </tr>
            <!-- EDP: ssl_block -->
        </table>
    </form>
</div>
