<div id="login">
    <form name="<?= toHtml($this->form->getName(), 'htmlAttr') ?>" method="post">
        <table>
            <tr>
                <td class="left"><label for="username"><?= toHtml($this->form->get('username')->getLabel()) ?></label></td>
                <td class="right">
                    <input type="text" name="username" id="username" value="<?= toHtml($this->form->get('username')->getValue(), 'htmlAttr') ?>">
                </td>
            </tr>
            <tr>
                <td class="left"><label for="password"><?= toHtml($this->form->get('password')->getLabel()) ?></label></td>
                <td class="right"><input type="password" name="password" id="password" value=""></td>
            </tr>
            <tr>
                <td colspan="2" class="right">
                    <input type="hidden" name="csrf" value="<?= toHtml($this->form->get('csrf')->getValue(), 'htmlAttr') ?>">
                    <button type="submit" name="submit" tabindex="3"><?= toHtml($this->form->get('submit')->getLabel()) ?></button>
                </td>
            </tr>
            <!-- BDP: ssl_block -->
            <tr>
                <td colspan="2" class="center">
                    <br>
                    <a class="icon {SSL_IMAGE_CLASS}" href="{SSL_LINK}" title="{TR_SSL_DESCRIPTION}">{TR_SSL}</a>
                </td>
            </tr>
            <!-- EDP: ssl_block -->
        </table>
    </form>
</div>
