
<script>
    $(function() {
        $('#domain_client_ips').multiSelect({
            selectableHeader: '<div class="ms-header"><?= toJs(tr('Available')); ?></div>',
            selectionHeader: '<div class="ms-header"><?= toJs(tr('Assigned')); ?></div>'
        });
    });
</script>

<form name="addCustomerFrm3" method="post" action="user_add3.php" autocomplete="off">
    <table class="firstColFixed">
        <thead>
        <tr>
            <th colspan="2"><?= toHtml(tr('Login data')); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><?= toHtml(tr('Username')); ?></td>
            <td><?= toHtml(decodeIdna($this->form->getValue('admin_name'))); ?></td>
        </tr>
        <tr>
            <td><label for="password"><?= toHtml(tr('Password')); ?></label></td>
            <td><input type="password" name="admin_pass" id="password" class="pwd_generator" value="" autocomplete="new-password" required></td>
        </tr>
        <tr>
            <td><label for="cpassword"><?= toHtml(tr('Password confirmation')); ?></label></td>
            <td><input type="password" name="admin_pass_confirmation" id="cpassword" value="" autocomplete="new-password" required></td>
        </tr>
        </tbody>
    </table>
    <table>
        <thead>
        <tr>
            <th><label for="domain_client_ips"><?= toHtml(tr('IP addresses')); ?></label></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <select id="domain_client_ips" name="domain_client_ips[]" multiple>
                    <!-- BDP: ip_entry -->
                    <option value="{IP_VALUE}"{IP_SELECTED}>{IP_NUM}</option>
                    <!-- EDP: ip_entry -->
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <table class="firstColFixed">
        <thead>
        <tr>
            <th colspan="2"><?= toHtml(tr('Personal data')); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><label for="fname"><?= toHtml(tr('First name')); ?></label></td>
            <td><input type="text" name="fname" id="fname" value="<?= toHtml($this->form->getValue('fname'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="lname"><?= toHtml(tr('Last name')); ?></label></td>
            <td><input type="text" name="lname" id="lname" value="<?= toHtml($this->form->getValue('lname'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="gender"><?= toHtml(tr('Gender')); ?></label></td>
            <td>
                <select id="gender" name="gender">
                    <option value="M"<?= $this->form->getValue('gender') == 'M' ? ' selected' : ''; ?>><?= toHtml(tr('Male')); ?></option>
                    <option value="F"<?= $this->form->getValue('gender') == 'F' ? ' selected' : ''; ?>><?= toHtml(tr('Female')); ?></option>
                    <option value="U"<?= $this->form->getValue('gender') == 'U' ? ' selected' : ''; ?>><?= toHtml(tr('Unknown')); ?></option>
                </select>
            </td>
        </tr>
        <tr>
            <td><label for="firm"><?= toHtml(tr('Company')); ?></label></td>
            <td><input type="text" name="firm" id="firm" value="<?= toHtml($this->form->getValue('firm'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="street1"><?= toHtml(tr('Street 1')); ?></label></td>
            <td><input type="text" name="street1" id="street1" value="<?= toHtml($this->form->getValue('street1'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="street2"><?= toHtml(tr('Street 2')); ?></label></td>
            <td><input type="text" name="street2" id="street2" value="<?= toHtml($this->form->getValue('street2'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="zip"><?= toHtml(tr('Zip/Postal code')); ?></label></td>
            <td><input type="text" name="zip" id="zip" value="<?= toHtml($this->form->getValue('zip'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="city"><?= toHtml(tr('City')); ?></label></td>
            <td><input type="text" name="city" id="city" value="<?= toHtml($this->form->getValue('city'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="state"><?= toHtml(tr('State/Province')); ?></label></td>
            <td><input type="text" name="state" id="state" value="<?= toHtml($this->form->getValue('state'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="country"><?= toHtml(tr('Country')); ?></label></td>
            <td><input type="text" name="country" id="country" value="<?= toHtml($this->form->getValue('country'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="email"><?= toHtml(tr('Email')); ?></label></td>
            <td><input type="text" name="email" id="email" value="<?= toHtml(decodeIdna($this->form->getValue('email')), 'htmlAttr'); ?>" required></td>
        </tr>
        <tr>
            <td><label for="phone"><?= toHtml(tr('Phone')); ?></label></td>
            <td><input type="text" name="phone" id="phone" value="<?= toHtml($this->form->getValue('phone'), 'htmlAttr'); ?>"></td>
        </tr>
        <tr>
            <td><label for="fax"><?= toHtml(tr('Fax')); ?></label></td>
            <td><input type="text" name="fax" id="fax" value="<?= toHtml($this->form->getValue('fax'), 'htmlAttr'); ?>"></td>
        </tr>
        </tbody>
    </table>
    <div class="buttons">
        <input name="Submit" type="submit" value="<?= toHtml(tr('Add'), 'htmlAttr'); ?>">
        <input type="hidden" name="uaction" value="user_add3_nxt">
    </div>
</form>
