<script>
    $(function () {
        $("#diskspace").on('keyup mouseup paste copy cut', function () {
            var storageQuotaLimit = parseInt($(this).val());
            var $mailQuotaField = $("#mail_quota");

            if (storageQuotaLimit > 0) {
                $mailQuotaField.attr("min", 1).attr("max", storageQuotaLimit);
                return;
            }

            $mailQuotaField.attr("min", 0).removeAttr("max");
        });
    });
</script>
<?php
    /** @var \Zend\Form\FieldsetInterface $limits */
    $limits = $this->form->get('limits');
    /** @var \Zend\Form\FieldsetInterface $features */
    $features = $this->form->get('features');
?>
<form name="<?= toHtml($this->form->getName(), 'htmlAttr') ?>" method="post">
    <table class="firstColFixed">
        <thead>
        <tr>
            <th colspan="2"><?= toHtml(tr('Hosting plan')) ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><label for="name"><?= toHtml($this->form->get('name')->getLabel()) ?></label></td>
            <td><input type="text" name="name" id="name" value="<?= toHtml($this->form->get('name')->getValue(), 'htmlAttr') ?>" class="inputTitle">
            </td>
        </tr>
        <tr>
            <td><label for="description"><?= toHtml($this->form->get('description')->getLabel()) ?></label></td>
            <td><textarea name="description" id="description"><?= toHtml($this->form->get('description')->getValue()) ?></textarea></td>
        </tr>
        </tbody>
    </table>
    <table class="firstColFixed">
        <thead>
        <tr>
            <th colspan="2"><?= toHtml(tr('Limits')) ?></th>
        </tr>
        </thead>
        <tbody>
        <? if(\iMSCP\Functions\Counting::userHasFeature('webDomains')): ?>
        <tr>
            <td>
                <label for="subdomain">
                    <?= toHtml($limits->get('domains')->getLabel()) ?><br>
                    <i>(-1 <?= toHtml(tr('disabled')) ?>, 0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[subdomain]" id="subdomain"
                       min="<?= toHtml($limits->get('domains')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('domains')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('domains')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        <? endif ?>
        <? if(\iMSCP\Functions\Counting::userHasFeature('webMailboxes')): ?>
        <tr>
            <td>
                <label for="mail_accounts">
                    <?= toHtml($limits->get('mail_accounts')->getLabel()) ?><br>
                    <i>(-1 <?= toHtml(tr('disabled')) ?>, 0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[mail_accounts]" id="mail_accounts"
                       min="<?= toHtml($limits->get('mail_accounts')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('mail_accounts')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('mail_accounts')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="mail_quota">
                    <?= toHtml($limits->get('mail_quota')->getLabel()) ?><br>
                    <i>(0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[mail_quota]" id="mail_quota"
                       min="<?= toHtml($limits->get('mail_quota')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('mail_quota')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('mail_quota')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        <? endif ?>
        <? if(\iMSCP\Functions\Counting::userHasFeature('ftp')): ?>
        <tr>
            <td>
                <label for="ftp_accounts">
                    <?= toHtml($limits->get('ftp_accounts')->getLabel()) ?><br>
                    <i>(-1 <?= toHtml(tr('disabled')) ?>, 0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[ftp_accounts]" id="ftp_accounts"
                       min="<?= toHtml($limits->get('ftp_accounts')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('ftp_accounts')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('ftp_accounts')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        <? endif ?>
        <? if(\iMSCP\Functions\Counting::userHasFeature('sql')): ?>
        <tr>
            <td>
                <label for="sql_databases">
                    <?= toHtml($limits->get('sql_databases')->getLabel()) ?><br>
                    <i>(-1 <?= toHtml(tr('disabled')) ?>, 0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[sql_databases]" id="sql_databases"
                       min="<?= toHtml($limits->get('sql_databases')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('sql_databases')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('sql_databases')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="sql_users">
                    <?= toHtml($limits->get('sql_users')->getLabel()) ?><br>
                    <i>(-1 <?= toHtml(tr('disabled')) ?>, 0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[sql_users]" id="sql_users"
                       min="<?= toHtml($limits->get('sql_users')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('sql_users')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('sql_users')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        <? endif ?>
        <tr>
            <td>
                <label for="monthly_traffic">
                    <?= $limits->get('monthly_traffic')->getLabel() ?><br>
                    <i>(0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[monthly_traffic]" id="monthly_traffic"
                       min="<?= toHtml($limits->get('monthly_traffic')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('monthly_traffic')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('monthly_traffic')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="diskspace">
                    <?= toHtml($limits->get('diskspace')->getLabel()) ?><br>
                    <i>(0 ∞)</i>
                </label>
            </td>
            <td>
                <input type="number" name="limits[diskspace]" id="diskspace"
                       min="<?= toHtml($limits->get('diskspace')->getAttribute('min'), 'htmlAttr') ?>"
                       max="<?= toHtml($limits->get('diskspace')->getAttribute('max'), 'htmlAttr') ?>"
                       value="<?= toHtml($limits->get('diskspace')->getValue(), 'htmlAttr') ?>">
            </td>
        </tr>
        </tbody>
    </table>
    <table class="firstColFixed">
        <thead>
        <tr>
            <th colspan="2"><?= toHtml(tr('Features')) ?>}</th>
        </tr>
        </thead>
        <tbody>
        <!-- BDP: php_feature -->
        <tr>
            <td><?= toHtml($features->get('php')->getLabel()) ?></td>
            <td>
                <div class="radio">
                    <label for="php_1">Yes</label>
                    <input type="radio" name="php" id="php_1" value="1"<?= $features->get('php')->getValue() == 1 ? ' checked' : '' ?>>
                    <label for="php_2">No</label>
                    <input type="radio" name="php" id="php_2" value="0"<?= $features->get('php')->getValue() == 0 ? ' checked' : '' ?>>
                </div>
            </td>
        </tr>
        <!-- EDP: php_feature -->
        <!-- BDP: php_editor_feature -->
        <tr id="php_editor_block">
            <td><label><?= toHtml(tr('PHP Editor')) ?></label></td>
            <td>
                <div class="radio">
                    <input type="radio" name="php_ini_system" id="php_ini_system_1" value="1"<?= $features->get('php')->getValue() == 1 ? ' checked' : '' ?>>
                    <label for="php_ini_system_1">{TR_YES}</label>
                    <input type="radio" name="php_ini_system" id="php_ini_system_0" value="0"<?= $features->get('php')->getValue() == 1 ? ' checked' : '' ?>>
                    <label for="php_ini_system_0">{TR_NO}</label>
                </div>
                <button type="button" id="php_editor_dialog_open"><?= toHtml(tr('Settings')) ?></button>
                <div id="php_editor_dialog" title="<?= toHtml(tr('PHP settings'), 'htmlAttr') ?>">
                    <div class="php_editor_error static_success">
                        <span id="php_editor_msg_default">{TR_FIELDS_OK}</span>
                    </div>
                    <!-- BDP: php_editor_permissions_block -->
                    <table>
                        <thead>
                        <tr>
                            <th colspan="2"><?= toHtml(tr('PHP permissions')) ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <!-- BDP: phpini_perm_config_level_block -->
                        <tr>
                            <td>
                                {TR_PHPINI_PERM_CONFIG_LEVEL}
                                <span class="icon i_help" title="{TR_PHPINI_PERM_CONFIG_LEVEL_HELP}"></span>
                            </td>
                            <td>
                                <div class="radio">
                                    <!-- BDP: phpini_perm_config_level_per_site_block -->
                                    <input type="radio" name="phpini_perm_config_level" id="phpini_perm_config_level_per_site" value="per_site"
                                           {PHPINI_PERM_CONFIG_LEVEL_PER_SITE}>
                                    <label for="phpini_perm_config_level_per_site">{TR_PER_SITE}</label>
                                    <!-- EDP: phpini_perm_config_level_per_site_block -->
                                    <input type="radio" name="phpini_perm_config_level" id="phpini_perm_config_level_per_domain" value="per_domain"
                                           {PHPINI_PERM_CONFIG_LEVEL_PER_DOMAIN}>
                                    <label for="phpini_perm_config_level_per_domain">{TR_PER_DOMAIN}</label>
                                    <input type="radio" name="phpini_perm_config_level" id="phpini_perm_config_level_per_user" value="per_user"
                                           {PHPINI_PERM_CONFIG_LEVEL_PER_USER}>
                                    <label for="phpini_perm_config_level_per_user">{TR_PER_USER}</label>
                                </div>
                            </td>
                        </tr>
                        <!-- EDP: phpini_perm_config_level_block -->
                        <!-- BDP: php_editor_allow_url_fopen_block -->
                        <tr>
                            <td>{TR_CAN_EDIT_ALLOW_URL_FOPEN}</td>
                            <td>
                                <div class="radio">
                                    <input type="radio" name="phpini_perm_allow_url_fopen" id="phpini_perm_allow_url_fopen_yes" value="yes"
                                           {ALLOW_URL_FOPEN_YES}>
                                    <label for="phpini_perm_allow_url_fopen_yes">{TR_YES}</label>
                                    <input type="radio" name="phpini_perm_allow_url_fopen" id="phpini_perm_allow_url_fopen_no" value="no"
                                           {ALLOW_URL_FOPEN_NO}>
                                    <label for="phpini_perm_allow_url_fopen_no">{TR_NO}</label>
                                </div>
                            </td>
                        </tr>
                        <!-- EDP: php_editor_allow_url_fopen_block -->
                        <!-- BDP: php_editor_display_errors_block -->
                        <tr>
                            <td>{TR_CAN_EDIT_DISPLAY_ERRORS}</td>
                            <td>
                                <div class="radio">
                                    <input type="radio" name="phpini_perm_display_errors" id="phpini_perm_display_errors_yes" value="yes"
                                           {DISPLAY_ERRORS_YES}>
                                    <label for="phpini_perm_display_errors_yes">{TR_YES}</label>
                                    <input type="radio" name="phpini_perm_display_errors" id="phpini_perm_display_errors_no" value="no"
                                           {DISPLAY_ERRORS_NO}>
                                    <label for="phpini_perm_display_errors_no">{TR_NO}</label>
                                </div>
                            </td>
                        </tr>
                        <!-- EDP: php_editor_display_errors_block -->
                        <!-- BDP: php_editor_disable_functions_block -->
                        <tr>
                            <td>{TR_CAN_EDIT_DISABLE_FUNCTIONS}</td>
                            <td>
                                <div class="radio">
                                    <input type="radio" name="phpini_perm_disable_functions" id="phpini_perm_disable_functions_yes" value="yes"
                                           {DISABLE_FUNCTIONS_YES}>
                                    <label for="phpini_perm_disable_functions_yes">{TR_YES}</label>
                                    <input type="radio" name="phpini_perm_disable_functions" id="phpini_perm_disable_functions_no" value="no"
                                           {DISABLE_FUNCTIONS_NO}>
                                    <label for="phpini_perm_disable_functions_no">{TR_NO}</label>
                                    <input type="radio" name="phpini_perm_disable_functions" id="phpini_perm_disable_functions_exec" value="exec"
                                           {DISABLE_FUNCTIONS_EXEC}>
                                    <label for="phpini_perm_disable_functions_exec">{TR_ONLY_EXEC}</label>
                                </div>
                            </td>
                        </tr>
                        <!-- EDP: php_editor_disable_functions_block -->
                        <!-- BDP: php_editor_mail_function_block -->
                        <tr>
                            <td>{TR_CAN_USE_MAIL_FUNCTION}</td>
                            <td>
                                <div class="radio">
                                    <input type="radio" name="phpini_perm_mail_function" id="phpini_perm_mail_function_yes" value="yes"
                                           {MAIL_FUNCTION_YES}>
                                    <label for="phpini_perm_mail_function_yes">{TR_YES}</label>
                                    <input type="radio" name="phpini_perm_mail_function" id="phpini_perm_mail_function_no" value="no"
                                           {MAIL_FUNCTION_NO}>
                                    <label for="phpini_perm_mail_function_no">{TR_NO}</label>
                                </div>
                            </td>
                        </tr>
                        <!-- EDP: php_editor_mail_function_block -->
                        </tbody>
                    </table>
                    <!-- EDP: php_editor_permissions_block -->
                    <!-- BDP: php_editor_default_values_block -->
                    <table>
                        <thead>
                        <tr>
                            <th colspan="2"><?= toHtml(tr('PHP limits')) ?></th>
                        </tr>
                        </thead>
                        <tbody id="php_ini_values">
                        <tr>
                            <td><label for="max_execution_time">{TR_MAX_EXECUTION_TIME}</label></td>
                            <td><input type="number" name="max_execution_time" id="max_execution_time" min="1" max="{MAX_EXECUTION_TIME}"
                                       value="{MAX_EXECUTION_TIME}"> <span>{TR_SEC}</span></td>
                        </tr>
                        <tr>
                            <td><label for="max_input_time">{TR_MAX_INPUT_TIME}</label></td>
                            <td><input type="number" name="max_input_time" id="max_input_time" min="1" max="{MAX_INPUT_TIME}"
                                       value="{MAX_INPUT_TIME}"> <span>{TR_SEC}</span></td>
                        </tr>
                        <tr>
                            <td><label for="memory">{TR_MEMORY}</label></td>
                            <td><input type="number" name="memory" id="memory" min="1" max="{MEMORY}" value="{MEMORY}">
                                <span>{TR_MIB}</span></td>
                        </tr>
                        <tr>
                            <td><label for="post_max_size">{TR_POST_MAX_SIZE}</label></td>
                            <td><input type="number" name="post_max_size" id="post_max_size" min="1" max="{POST_MAX_SIZE}"
                                       value="{POST_MAX_SIZE}"> <span>{TR_MIB}</span></td>
                        </tr>
                        <tr>
                            <td><label for="upload_max_filesize">{TR_UPLOAD_MAX_FILEZISE}</label></td>
                            <td><input type="number" name="upload_max_filesize" id="upload_max_filesize" min="1" max="{UPLOAD_MAX_FILESIZE}"
                                       value="{UPLOAD_MAX_FILESIZE}"> <span>{TR_MIB}</span></td>
                        </tr>
                        </tbody>
                    </table>
                    <!-- EDP: php_editor_default_values_block -->
                </div>
            </td>
        </tr>
        <!-- EDP: php_editor_feature -->
        <!-- BDP: cgi_feature -->
        <tr>
            <td>{TR_CGI}</td>
            <td>
                <div class="radio">
                    <input type="radio" name="cgi" value="_yes_" id="cgi_yes" {CGI_YES}>
                    <label for="cgi_yes">{TR_YES}</label>
                    <input type="radio" name="cgi" value="_no_" id="cgi_no" {CGI_NO}>
                    <label for="cgi_no">{TR_NO}</label>
                </div>
            </td>
        </tr>
        <!-- EDP: cgi_feature -->
        <!-- BDP: custom_dns_records_feature -->
        <tr>
            <td>{TR_DNS}</td>
            <td>
                <div class="radio">
                    <input type="radio" name="dns" value="_yes_" id="dns_yes" {DNS_YES}>
                    <label for="dns_yes">{TR_YES}</label>
                    <input type="radio" name="dns" value="_no_" id="dns_no" {DNS_NO}>
                    <label for="dns_no">{TR_NO}</label>
                </div>
            </td>
        </tr>
        <!-- EDP: custom_dns_records_feature -->
        <!-- BDP: ext_mail_feature -->
        <tr>
            <td>{TR_EXTMAIL}</td>
            <td>
                <div class="radio">
                    <input type="radio" name="external_mail" value="_yes_" id="extmail_yes" {EXTMAIL_YES}>
                    <label for="extmail_yes">{TR_YES}</label>
                    <input type="radio" name="external_mail" value="_no_" id="extmail_no" {EXTMAIL_NO}>
                    <label for="extmail_no">{TR_NO}</label>
                </div>
            </td>
        </tr>
        <!-- EDP: ext_mail_feature -->
        <!-- BDP: backup_feature -->
        <tr>
            <td>{TR_BACKUP}</td>
            <td>
                <div class="checkbox">
                    <input type="checkbox" name="backup[]" value="_dmn_" id="backup_dmn" {VL_BACKUPD}>
                    <label for="backup_dmn">{TR_BACKUP_DOMAIN}</label>
                    <input type="checkbox" name="backup[]" value="_sql_" id="backup_sql" {VL_BACKUPS}>
                    <label for="backup_sql">{TR_BACKUP_SQL}</label>
                    <input type="checkbox" name="backup[]" value="_mail_" id="backup_mail" {VL_BACKUPM}>
                    <label for="backup_mail">{TR_BACKUP_MAIL}</label>
                </div>
            </td>
        </tr>
        <!-- EDP: backup_feature -->
        <tr>
            <td>
                <label>{TR_WEB_FOLDER_PROTECTION}</label>
                <span class="icon i_help" id="web_folder_protection_help" title="{TR_WEB_FOLDER_PROTECTION_HELP}"></span>
            </td>
            <td>
                <div class="radio">
                    <input type="radio" name="protected_webfolders" value="_yes_" id="protected_webfolders_yes" {PROTECT_WEB_FOLDERS_YES}>
                    <label for="protected_webfolders_yes">{TR_YES}</label>
                    <input type="radio" name="protected_webfolders" value="_no_" id="protected_webfolders_no" {PROTECT_WEB_FOLDERS_NO}>
                    <label for="protected_webfolders_no">{TR_NO}</label>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <table class="firstColFixed">
        <thead>
        <tr>
            <th colspan="2">{TR_HP_AVAILABILITY}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{TR_STATUS}</td>
            <td>
                <div class="radio">
                    <input type="radio" name="status" value="1" id="status_yes" {STATUS_YES}>
                    <label for="status_yes">{TR_YES}</label>
                    <input type="radio" name="status" value="0" id="status_no" {STATUS_NO}>
                    <label for="status_no">{TR_NO}</label>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="buttons">
        <input type="hidden" name="csrf" value="<?= toHtml($this->form->get('csrf')->getValue(), 'htmlAttr') ?>">
        <input name="submit" type="submit" value="<?= toHtml($this->form->get('submit')->getLabel(), 'htmlAttr') ?>">
        <a class="link_as_button" href="hosting_plan.php"><?= toHtml(tr('Cancel')) ?></a>
    </div>
</form>
