<script>
    function action_delete(link) {
        return jQuery.imscp.confirmOnclick(
            link, "<?= toJs(tr('Are you sure you want to delete this account?')); ?>"
        );
    }

    $(function() {
        $("#administrators_table, #resellers_table").dataTable({
            language: <?= \iMSCP\Functions\View::getDataTablesPluginTranslations(); ?>,
            displayLength: 10,
            stateSave: true,
            pagingType: "simple",
            columnDefs: [{sortable: false, searchable: false, targets: [3]}]
        });
    });
</script>
<h3 class="user_yellow"><span><?= toHtml(tr('Administrator accounts')); ?></span></h3>
<!-- BDP: administrator_message -->
<div class="static_info"><?= toHtml(tr('No account found.')); ?></div>
<!-- EDP: administrator_message -->
<!-- BDP: administrator_list -->
<table class="firstColFixed" id="administrators_table">
    <thead>
    <tr>
        <th><?= toHtml(tr('Username')); ?></th>
        <th><?= toHtml(tr('Created on')); ?></th>
        <th><?= toHtml(tr('created by')); ?></th>
        <th><?= toHtml(tr('Actions')); ?></th>
    </tr>
    </thead>
    <tbody>
    <!-- BDP: administrator_item -->
    <tr>
        <td>{ADMINISTRATOR_USERNAME}</td>
        <td>{ADMINISTRATOR_CREATED_ON}</td>
        <td>{ADMINISTRATPR_CREATED_BY}</td>
        <td>
            <a href="user_edit.php?edit_id={ADMINISTRATOR_ID}" class="icon i_user" title="<?= toHtml(tr('Edit'), 'htmlAttr'); ?>"><?= toHtml(tr('Edit')); ?></a>
            <!-- BDP: administrator_delete_link -->
            <a href="user_delete.php?delete_id={ADMINISTRATOR_ID}" class="icon i_delete" onclick="return action_delete(this)" title="<?= toHtml(tr('Delete'), 'htmlAttr'); ?>"><?= toHtml(tr('Delete')); ?></a>
            <!-- EDP: administrator_delete_link -->
        </td>
    </tr>
    <!-- EDP: administrator_item -->
    </tbody>
</table>
<!-- EDP: administrator_list -->
<h3 class="user_green"><span><?= toHtml(tr('Reseller accounts')); ?></span></h3>
<!-- BDP: reseller_message -->
<div class="static_info"><?= toHtml(tr('No account found.')); ?></div>
<!-- EDP: reseller_message -->
<!-- BDP: reseller_list -->
<table class="firstColFixed" id="resellers_table">
    <thead>
    <tr>
        <th><?= toHtml(tr('Username')); ?></th>
        <th><?= toHtml(tr('Created on')); ?></th>
        <th><?= toHtml(tr('Created by')); ?></th>
        <th><?= toHtml(tr('Action')); ?></th>
    </tr>
    </thead>
    <tbody>
    <!-- BDP: reseller_item -->
    <tr>
        <td>{RESELLER_USERNAME}</td>
        <td>{RESELLER_CREATED_ON}</td>
        <td>{RESELLER_CREATED_BY}</td>
        <td>
            <a class="icon i_details" href="change_user_interface.php?to_id={RESELLER_ID}" title="<?= toHtml(tr('Switch to user interface'), 'htmlAttr'); ?>"><?= toHtml(tr('Switch')); ?></a>
            <a href="reseller_edit.php?edit_id={RESELLER_ID}" class="icon i_user" title="<?= toHtml(tr('Edit this reseller account'), 'htmlAttr'); ?>"><?= toHtml(tr('Edit')); ?></a>
            <a href="user_delete.php?delete_id={RESELLER_ID}" class="icon i_delete" title="<?= toHtml(tr('Delete this reseller, including all its customers'), 'htmlAttr'); ?>" onclick="return action_delete(this)"><?= toHtml(tr('Delete')); ?></a>
        </td>
    </tr>
    <!-- EDP: reseller_item -->
    </tbody>
</table>
<!-- EDP: reseller_list -->
<!-- INCLUDE shared/partials/client_list.phtml -->
